### ISSUE TITLE
No Output/Dockerfile won't run

### ISSUE THREAD

**Issue by Joniator** [left4craft/spigot-updater#3]
This sounds like a really usefull tool that is almost tailored to my usecase, but I can't get the Dockerfile from the docs to work.

I copied it one for one, it built successfull, but in Pterodactyl I get no output at all, and if I run the image it won't run either.
It won't find the user container, and when I force root, it won't find the command ip:

```
$ docker run --rm puppeteer-chrome-linux:latest
docker: Error response from daemon: unable to find user container: no matching entries in passwd file.

$ docker run --rm -u root puppeteer-chrome-linux:latest
/entrypoint.sh: line 5: ip: command not found
:/home/container$
```

The documentation is a little older at this point, is it still up to date? If yes, what am I missing?
Running in pterodactyl doesn't produce any output, not even the :/home/container$, just an endless black screen after the image was successfully pulled and started.

Help or hints would be appreciated :)

**Comment by Joniator** [comment]
I got it running, I did not realize that all the logs are only written to file except stderr (?).

At least now everything is configured. But because the logs are only written to file, Ptero detects the updater as starting. The last commit added a log message specifically for that, so I guess there is a setup where the logs also appear on stdout?

Currently the write_logs seems to be useless, the logs always end up only in the logfile, never on stdout.

I still have the errors, but they don't seem to impact usability (at least it notified me about a paper update).
The following is everything he logged in pterodactyl since the image was pulled/server was marked starting

'''
/entrypoint.sh: line 5: ip: command not found
(node:28) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
'''

**Comment by eartharoid** [comment]
> all the logs are only written to file except stderr 

There should be text logged to the console when the bot connects to Discord.

**Comment by Joniator** [comment]
I don't have any. 
When I restart/start the plugin:

```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image

```

The Logfle:

```
	❯ A leekslazylogger project
	❯ Powered by leekslazylogger v4.1.3
	❯ Log level "info"
	❯ Node.js v16.13.1 on linux
	❯ Tuesday, 11 January 2022 at 16:07 PM (Europe/Berlin) -->

[11/01/22 16:07:20] [INFO] Connecting to database
[11/01/22 16:07:20] [INFO] Connecting to Discord API
[11/01/22 16:07:20] [SUCCESS] Authenticated as Spigot Updater#6951
[11/01/22 16:07:20] [SUCCESS] Connected to Discord API
[11/01/22 16:07:20] [INFO] Running daily update check task
[11/01/22 16:07:20] [INFO] Checking for server jar updates
[11/01/22 16:07:21] [INFO] Found an update for Paper 
[11/01/22 16:07:21] [INFO] Checking for plugin updates
[11/01/22 16:07:21] [INFO] Checking for updates for plugins on SpigotMC
[11/01/22 16:07:21] [INFO] Starting browser
[11/01/22 16:07:22] [INFO] Loading spigotmc.org (waiting for Cloudflare)
[11/01/22 16:07:22] [INFO] Loaded spigotmc.org! Saving screenshot as loaded.png...
[11/01/22 16:07:33] [INFO] Already logged in!
```

When I reload the pterodactyl terminal (After the text appeared in the log/the bot wrote in it's discord channel):
```
container@pterodactyl~ Server marked as starting...
/entrypoint.sh: line 5: ip: command not found
(node:28) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


```

My config.js looks like this:

```
module.exports = {
	server_name: '[...]',
	color: '#C10053',
	channel_id: '[...]',
	server_jars_api: 'papermc',
	headless_browser: true,
	no_sandbox_browser: true, // only change to true if you are getting errors or using docker
	cloudflare_timeout: 300000, // time to wait to pass cloudflare Javascript challenge
	navigation_delay: 10000, // delay between navigating spigotmc pages
	download_time: 10000, // 10-15 seconds recommended, 5 seconds for Cloudflare
	save_logs: true,
	debug: false,
};
```

The Dockerfile/Entrypoint: 
```
::::::::::::::
Dockerfile
::::::::::::::
FROM node:lts-slim

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y wget gnupg git \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         ["/bin/bash", "/entrypoint.sh"]
::::::::::::::
entrypoint.sh
::::::::::::::
#!/bin/ash
cd /home/container

# Make internal Docker IP address available to processes.
export INTERNAL_IP=`ip route get 1 | awk '{print $NF;exit}'`

# Replace Startup Variables
MODIFIED_STARTUP=`eval echo $(echo ${STARTUP} | sed -e 's/{{/${/g' -e 's/}}/}/g')`
echo ":/home/container$ ${MODIFIED_STARTUP}"

# Run the Server
eval ${MODIFIED_STARTUP}
```

The only thing I adjusted is the startup command, since the default one does not do anything, no log, no output, no discord:

```
npm i; npm start
```

**Comment by CaptnSisko** [comment]
The docs are a bit out of date, sorry about that. I don't think the extra ip configuration is still necessary, so you could try changing entrypoint.sh to
```
#!/bin/ash
cd /home/container
eval ${STARTUP}
```
and rebuilding the container. 

Also, the startup command I'm using is `/usr/local/bin/npm install; /usr/local/bin/node /home/container/src/index.js`, but I'm not sure if that makes a difference

**Comment by Joniator** [comment]
Thank you for the quick response, I changed the entrypoint and the startup command, and it works now. 

Somehow pterodactyl doesn't automatically update new log lines (which works on other server) and I have to hit reload by hand. Maybe thats on pteros side, but weird nontheless.I guess I'll figure it out, but as long as it works its not really a priority for me.

I'll update if I find something, but from my side this can be closed.
